# Generated by Django 5.0 on 2025-11-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_item_price_remove_order_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
