# Generated by Django 5.2.8 on 2025-11-12 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_branches_and_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('zh-hans', 'Chinese (Simplified)'), ('ja', 'Japanese'), ('pt', 'Portuguese'), ('hi', 'Hindi')], max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='movies.movie')),
            ],
            options={
                'verbose_name': 'Movie Translation',
                'verbose_name_plural': 'Movie Translations',
                'unique_together': {('movie', 'language_code')},
            },
        ),
    ]
