# Generated by Django 5.2.8 on 2025-11-12 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_movietranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='movietranslation',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movietranslation',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
